config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create, :index, :destroy]
  end
  resources :bookmarks, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    # raise
    # @list = List.find(params[:list_id])
    # @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render template: "lists/show"
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
    @movies = @list.movies
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/evlkOfkQ5rE/1600x900);">
  <div class="container text-center">
    <h1>pmdb</h1>
    <p>Manage your movie lists</p>
    <%= link_to 'Create new list', new_list_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/lists/_card.html.erb
<div class="card-trip col-4 my-3">
  <img src="<%= movie.poster_url %>" />
  <div class="card-trip-infos">
    <div>
      <h2><%= movie.title %></h2>
      <p><%= movie.overview %></p>
    </div>
    <h2 class="card-trip-pricing">⭐️ <%= movie.rating %></h2>
  </div>
</div>

app/views/lists/_categorybanner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path list.photo.key, height: 900, width: 1440, crop: :fill %>);">
  <div class="container text-center">
    <h2><%= list.name %> movies</h2>
  </div>
</div>

app/views/lists/_listcard.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>), url(https://source.unsplash.com/1600x900/?movie)">
  <%= list.name %>
</div>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "clapperboard.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", lists_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New list", new_list_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/lists/index.html.erb
<%= render 'banner' %>

<div class="container mt-4">
  <div class="row">
  <% @lists.each do |list| %>
    <div class= "col-4">
      <%= link_to list_path(list), class:'text-decoration-none' do %>
        <%= render 'listcard', list: list %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.submit 'Create a new list' %>
<% end %>

app/views/lists/show.html.erb
<%= render 'categorybanner', list: @list %>
<br>
<% @bookmarks.each_with_index do |bookmark, index| %>
  <p><%= "#{index+1}: #{bookmark.movie.title} - #{bookmark.comment}" %></p>
  <%= link_to 'Delete bookmark', [bookmark.list, bookmark],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
<% end %>

<div class="container">
    <div class="row">
<% @movies.each do |movie| %>
      <%= render 'card', movie: movie %>
<% end %>
    </div>
</div>


<h3>Submit a comment</h3>
<%= simple_form_for @bookmark do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit, class: "btn btn-secondary" %>
<% end %>

<%= link_to 'Back to lists', lists_path, class: "btn btn-primary"%>